"""cabinet invites

Revision ID: ebe64dff28b0
Revises: 20e2518a3d0a
Create Date: 2026-09-06 20:30:58.758232
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ebe64dff28b0"
down_revision: str | None = "20e2518a3d0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_invites_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_invites")),
    )
    op.create_index(
        op.f("ix_account_invites_account_id"),
        "account_invites",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_invites_created_at"),
        "account_invites",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_invites_token_hash"),
        "account_invites",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_invites_token_hash"), table_name="account_invites")
    op.drop_index(op.f("ix_account_invites_created_at"), table_name="account_invites")
    op.drop_index(op.f("ix_account_invites_account_id"), table_name="account_invites")
    op.drop_table("account_invites")
    # ### end Alembic commands ###
