"""client cabinet

Revision ID: 20e2518a3d0a
Revises: 71a204aec096
Create Date: 2026-09-04 19:43:29.372788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20e2518a3d0a"
down_revision: str | None = "71a204aec096"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["accounts.id"],
            name=op.f("fk_account_sessions_owner_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_sessions")),
    )
    op.create_index(
        op.f("ix_account_sessions_created_at"),
        "account_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_sessions_owner_id"),
        "account_sessions",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_sessions_token_hash"),
        "account_sessions",
        ["token_hash"],
        unique=True,
    )
    # server_default обязателен: колонка добавляется в непустую таблицу.
    # После заполнения умолчание снимается — дальше значение задаёт приложение.
    op.add_column(
        "accounts",
        sa.Column("failed_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("accounts", "failed_attempts", server_default=None)
    op.add_column(
        "accounts", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "accounts",
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    # Колонка admin_id переименована в owner_id: сессии панели и кабинета
    # теперь описываются общей моделью. Открытые сессии при этом
    # закрываются — переносить их между колонками смысла нет, вход
    # выполняется заново.
    op.execute(sa.text("DELETE FROM admin_sessions"))
    op.drop_index(op.f("ix_admin_sessions_admin_id"), table_name="admin_sessions")
    op.drop_constraint(
        op.f("fk_admin_sessions_admin_id_admin_users"),
        "admin_sessions",
        type_="foreignkey",
    )
    op.drop_column("admin_sessions", "admin_id")
    op.add_column("admin_sessions", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_admin_sessions_owner_id"), "admin_sessions", ["owner_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_admin_sessions_owner_id_admin_users"),
        "admin_sessions",
        "admin_users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM admin_sessions"))
    op.drop_constraint(
        op.f("fk_admin_sessions_owner_id_admin_users"),
        "admin_sessions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_admin_sessions_owner_id"), table_name="admin_sessions")
    op.drop_column("admin_sessions", "owner_id")
    op.add_column(
        "admin_sessions",
        sa.Column("admin_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_id"), "admin_sessions", ["admin_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_admin_sessions_admin_id_admin_users"),
        "admin_sessions",
        "admin_users",
        ["admin_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("accounts", "last_login_at")
    op.drop_column("accounts", "locked_until")
    op.drop_column("accounts", "failed_attempts")
    op.drop_index(op.f("ix_account_sessions_token_hash"), table_name="account_sessions")
    op.drop_index(op.f("ix_account_sessions_owner_id"), table_name="account_sessions")
    op.drop_index(op.f("ix_account_sessions_created_at"), table_name="account_sessions")
    op.drop_table("account_sessions")
    # ### end Alembic commands ###
