"""admin panel and savings stats

Revision ID: 71a204aec096
Revises: 966bc90d519d
Create Date: 2026-09-02 22:32:48.204103
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

DEFAULT_ACQUIRING_FEE_BPS = 70
"""Ставка эквайринга для организаций, заведённых до появления колонки.

Значение зафиксировано в миграции намеренно: миграция описывает состояние
базы на конкретный момент и не должна меняться вслед за настройками.
"""

revision: str = "71a204aec096"
down_revision: str | None = "966bc90d519d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("totp_secret", sa.String(length=32), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
    )
    op.create_index(
        op.f("ix_admin_users_created_at"), "admin_users", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_sessions_admin_id_admin_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_id"), "admin_sessions", ["admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_admin_sessions_created_at"),
        "admin_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_sessions_token_hash"),
        "admin_sessions",
        ["token_hash"],
        unique=True,
    )
    # server_default обязателен: колонки добавляются в таблицы, где уже есть
    # строки, и без значения по умолчанию база откажется делать их NOT NULL.
    # После заполнения умолчание снимается — дальше значение задаёт приложение.
    op.add_column(
        "accounts",
        sa.Column(
            "is_unlimited", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.alter_column("accounts", "is_unlimited", server_default=None)

    op.add_column(
        "organizations",
        sa.Column(
            "acquiring_fee_bps",
            sa.Integer(),
            nullable=False,
            server_default=sa.text(str(DEFAULT_ACQUIRING_FEE_BPS)),
        ),
    )
    op.alter_column("organizations", "acquiring_fee_bps", server_default=None)
    op.add_column(
        "organizations",
        sa.Column("average_check_kopecks", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "average_check_kopecks")
    op.drop_column("organizations", "acquiring_fee_bps")
    op.drop_column("accounts", "is_unlimited")
    op.drop_index(op.f("ix_admin_sessions_token_hash"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_created_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_id"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_index(op.f("ix_admin_users_created_at"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
