"""initial schema

Revision ID: af85910a15f3
Revises:
Create Date: 2026-09-01 11:54:45.366689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "af85910a15f3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("balance_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("overdraft_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("overdraft_extensions_used", sa.Integer(), nullable=False),
        sa.Column("daily_charge_limit_kopecks", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(
        op.f("ix_accounts_created_at"), "accounts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_api_tokens_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
    )
    op.create_index(
        op.f("ix_api_tokens_account_id"), "api_tokens", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_tokens_created_at"), "api_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_api_tokens_token_hash"), "api_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("personal_acc", sa.String(length=20), nullable=False),
        sa.Column("bank_name", sa.String(length=45), nullable=False),
        sa.Column("bic", sa.String(length=9), nullable=False),
        sa.Column("corresp_acc", sa.String(length=20), nullable=False),
        sa.Column("payee_inn", sa.String(length=12), nullable=False),
        sa.Column("kpp", sa.String(length=9), nullable=True),
        sa.Column("logo_key", sa.String(length=255), nullable=True),
        sa.Column("qr_color", sa.String(length=7), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_organizations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint(
            "account_id", "alias", name="uq_organizations_account_alias"
        ),
    )
    op.create_index(
        op.f("ix_organizations_account_id"),
        "organizations",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_created_at"),
        "organizations",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("public_token", sa.String(length=32), nullable=False),
        sa.Column("sum_kopecks", sa.BigInteger(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("charge_count", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_invoices_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invoices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_index(
        op.f("ix_invoices_account_id"), "invoices", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_created_at"), "invoices", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_idempotency_key"),
        "invoices",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_invoices_organization_id"),
        "invoices",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoices_public_token"), "invoices", ["public_token"], unique=True
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column(
            "entry_type",
            sa.Enum(
                "TOPUP",
                "CHARGE",
                "REFUND",
                "ADJUSTMENT",
                name="ledgerentrytype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("amount_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_kopecks <> 0", name=op.f("ck_ledger_entries_amount_not_zero")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_ledger_entries_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_ledger_entries_invoice_id_invoices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(
        op.f("ix_ledger_entries_account_id"),
        "ledger_entries",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ledger_entries_created_at"),
        "ledger_entries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ledger_entries_invoice_id"),
        "ledger_entries",
        ["invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ledger_entries_invoice_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_created_at"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_account_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_invoices_public_token"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_idempotency_key"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_created_at"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_account_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_account_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_api_tokens_token_hash"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_created_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_account_id"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_created_at"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
